### PR TITLE
Update TimestampableEntity.php for compat with ORM v3

### PR DESCRIPTION
**Pull request by andreybolonin**
https://github.com/doctrine-extensions/DoctrineExtensions/issues/2708#issuecomment-1931650181

### CODE REVIEW

**Comment by mbabker** [comment]
This is an incorrect fix as it removes annotation support entirely.  The presence of annotations when installed alongside ORM 3.0 in and of itself isn't an issue, unless, your application is still using annotations for something outside the ORM and this package's mapping and those annotations are being read by that process.  In that case, you should add a call to `Doctrine\Common\Annotations\AnnotationReader::addGlobalIgnoredNamespace('Doctrine\ORM\Mapping')` so the annotation reader service in your application ignores the ORM's mapping classes.

As well, this package does not yet support ORM 3.0.  You should downgrade your application to ORM 2.18 and continue using that until all dependencies are compatible with the new major release.

**Comment by mishac** [comment]
In that case shouldn't the composer.json indicate the conflict with ORM > 2?

**Comment by mbabker** [comment]
> In that case shouldn't the composer.json indicate the conflict with ORM > 2?

Probably should've been done sooner, but #2759

**Comment by franmomu** [comment]
Closing as this is not right as explained in https://github.com/doctrine-extensions/DoctrineExtensions/pull/2757#issuecomment-1934260512

**Pull request closed without merging**
