### PR TITLE
Migrate to Github Actions

### PR DESCRIPTION
**Pull request by franmomu**
It has added a test for lowest dependencies, the result can be seen in: https://github.com/franmomu/DoctrineExtensions/pull/1

### CODE REVIEW

**Review by stephanvierkant — APPROVED** [review]
Looks good to me!

**Review by svycka — APPROVED** [review]
I would like a code style check added but other than this I guess all ok if you tested.

**Comment by franmomu** [comment]
> I would like a code style check added but other than this I guess all ok if you tested.

I think that deserves another file (and PR because code style should be fixed first), this is just about migrating the existing travis configuration to Github Actions.

**Comment by svycka** [comment]
> > I would like a code style check added but other than this I guess all ok if you tested.
> 
> I think that deserves another file (and PR because code style should be fixed first), this is just about migrating the existing travis configuration to Github Actions.

**Pull request merged**
