### PR TITLE
chore: Add tests for PHP 8.4

### PR DESCRIPTION
**Pull request by Chris53897**

### CODE REVIEW

**Comment by Chris53897** [comment]
@phansys CI is green now.
php-cs-fixer  should be handled in seperate PR i guess,

**Comment by phansys** [comment]
So, what prevent us to bump the PHP version in the remaining workflow jobs?

https://github.com/doctrine-extensions/DoctrineExtensions/blob/132d483a7d46740aefecdf2b6342f6b3d7b3a047/.github/workflows/qa.yml#L22

https://github.com/doctrine-extensions/DoctrineExtensions/blob/132d483a7d46740aefecdf2b6342f6b3d7b3a047/.github/workflows/coding-standards.yml#L22

https://github.com/doctrine-extensions/DoctrineExtensions/blob/132d483a7d46740aefecdf2b6342f6b3d7b3a047/.github/workflows/coding-standards.yml#L43

https://github.com/doctrine-extensions/DoctrineExtensions/blob/132d483a7d46740aefecdf2b6342f6b3d7b3a047/.github/workflows/coding-standards.yml#L68

**Comment by Chris53897** [comment]
Sorry. Now i get your point.

PHP-CS-Fixer needs to be at PHP 8.3.
I updated the others.

**Comment by phansys** [comment]
Thank you @Chris53897!

**Pull request merged**
