### PR TITLE
[documentation] Updates docker-compose related commands in README

### PR DESCRIPTION
**Pull request by JoolsMcFly**
Hi,

`docker compose` needs to be changed to `docker-compose` and since you are not using the default `docker-compose.yaml` file then we need to use `-f ./compose.yaml` for commands to work.

Thanks!

### CODE REVIEW

**Comment by phansys** [comment]
Thank you @JoolsMcFly.
Please, note that the current implementation is using the [Docker Compose plugin](https://docs.docker.com/compose/install/linux/), which provides the `docker compose` command.
About the compose file, `compose.yaml` is currently the first file that the command looks for. See [Compose file](https://docs.docker.com/compose/compose-file/#compose-file).

**Comment by JoolsMcFly** [comment]
Right, so ... useless PR?

**Comment by phansys** [comment]
IMO, not useless at all, but I think we can safely close this one based on our current implementation.
Thank you very much!

**Comment by JoolsMcFly** [comment]
Closing as `docker compose` is legit! :)

**Pull request closed without merging**
