### PR TITLE
Add Coding standards check for Github Actions

### PR DESCRIPTION
**Pull request by franmomu**
Triggered by https://github.com/doctrine-extensions/DoctrineExtensions/pull/2214#pullrequestreview-649006936, this adds a coding standards check job for Github Actions.

~It is draft because~ there are a couple of things to discuss, the job can be seen in https://github.com/franmomu/DoctrineExtensions/pull/4

Seeing the changes proposed by `php-cs-fixer`, just a couple of questions:

```diff
--- Original
+++ New
@@ @@
         if (isset($mapping->field)) {
-            /**
+            /*
              * @var \SimpleXmlElement
              */
```
Is this change ok? or should we change [`phpdoc_to_comment`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.18/doc/rules/phpdoc/phpdoc_to_comment.rst)? to not remove this.

And the other one:

```diff
--- Original
+++ New
@@ @@
                 // update translation
-                if ($translated !== null
+                if (null !== $translated
```

I personally [don't like yoda conditions](https://dev.to/greg0ire/why-using-yoda-conditions-you-should-probably-not), I would disable them, but it's not my call.

### CODE REVIEW

**Review by phansys — APPROVED** [review]

**Comment by svycka** [comment]
```diff
--- Original
+++ New
@@ @@
         if (isset($mapping->field)) {
-            /**
+            /*
              * @var \SimpleXmlElement
              */
````
I vote to keep the old one `/**`
````diff
--- Original
+++ New
@@ @@
                 // update translation
-                if ($translated !== null
+                if (null !== $translated
````
I am ok with this change

**Comment by stephanvierkant** [comment]
> I personally don't like yoda conditions, I would disable them, but it's not my call.
Hear hear! I really hate it. The only reason one want to use it is invalid since the invention of modern static analysers.

Let's use the Doctrine Coding Standard.

**Comment by franmomu** [comment]
I would use Doctrine Coding Standard too, but it would require some more work, IMHO this could be merge as is for new PRs to stick to a CS and another PR could be done to change to Doctrine CS.

**Comment by AkenRoberts** [comment]
Thank you!

I am anti-Yoda condition as well, but that can be dialed in another time. Consistency is more important than what I prefer as an individual.

And agreed on getting this started and possibly moving to Doctrine Coding Standard in the future.

**Pull request merged**
