### PR TITLE
Remplace getEntityManager by getObjectManager to remove deprecation message symfony 6.3 (#2664)

### PR DESCRIPTION
**Pull request by yobrx**
https://github.com/doctrine-extensions/DoctrineExtensions/issues/2664

### CODE REVIEW

**Comment by phpremco** [comment]
Hi, thanks for the commit. The getEntity() also needs changed in the same way -> getObject(), see my other comment. I will have a look into how i can make commits in the future to help out, it feels a bit silly to wait while i have working code ready haha.

**Comment by yobrx** [comment]
Hi, you're welcome !

This patch fixes a production application writing too many depreciation alerts to a file which is filling up my disk space :)

**Comment by yobrx** [comment]
For testing, in composer.json :

```json
{
   "repositories": [
        {
            "type": "git",
            "url": "https://github.com/yobrx/DoctrineExtensions.git"
        }
    ],
    "require": {
        "gedmo/doctrine-extensions": "dev-object_manager"
    }
}
```

**Comment by DubbleClick** [comment]
This is missing much more than just that one instance. See https://github.com/doctrine-extensions/DoctrineExtensions/pull/2639

**Comment by franmomu** [comment]
Closing here since https://github.com/doctrine-extensions/DoctrineExtensions/pull/2639 was merged, thanks @yobrx!

**Pull request closed without merging**
