### PR TITLE
chore: make dataproviders static for phpunit 10

### PR DESCRIPTION
**Pull request by Chris53897**
to prepare for phpunit 10

### CODE REVIEW

**Comment by phansys** [comment]
[phpunit/phppunit:10.0.0](https://github.com/sebastianbergmann/phpunit/releases/tag/10.0.0) was released on 2023-02-03.
Could you please confirm if it is compatible with our setup?
https://github.com/doctrine-extensions/DoctrineExtensions/blob/792dda6fbb91a52c4dc0d3d405b1601ec138bcc6/composer.json#L65

**Comment by Chris53897** [comment]
This bundle/tests are not yet compatible with PHPUnit 10.

Direct: Tests withConsecutive() needs to be rewritten. I am not sure if there is more. I prepared a Branch locally
Indirect: symfony/phpunit-bridge is not yet compatible

This is just to prepare for version 10. Tests without static data generators will raise a warning in PHPUnit 10.

**Comment by Chris53897** [comment]
Maybe i got your question wrong. (The runner for php 7.3 and 8.0 are stuck.)
These changes should be safe for older phpunit version. If this was your question did targed.

**Comment by phansys** [comment]
>Maybe i got your question wrong. (The runner for php 7.3 and 8.0 are stuck.)

No, that's exactly what I was wondering. Thanks.

**Comment by Chris53897** [comment]
8.1 runner is stucked again i guess ;(

**Comment by phansys** [comment]
Thanks @Chris53897!

**Pull request merged**
