### PR TITLE
[Loggable] Map nested embeddables

### PR DESCRIPTION
**Pull request by robertburczak**
Possibility to map nested embeddables in yaml mappings.
Thanks @ghettovoice for suggestion

### CODE REVIEW

**Comment by mkosiedowski** [comment]
Any chances of merging that PR? :) We are using our fork with that change for over a year now and would love to switch back to original version of DoctrineExtensions... @AkenRoberts?

**Comment by AkenRoberts** [comment]
I'd consider adding to the upcoming 3.0 release in `master`, I'd just need to familiarize myself with what this changes, and if we want to test for it. It doesn't break anything, which is a good start. I just want to avoid adding untested features.

**Comment by andrekutianski** [comment]
Didn't this PR enter version 3?

**Comment by franmomu** [comment]
thanks for the time invested in this PR and sorry for the delay. The Yaml drives has been deprecated, you should use `Attribute`,  `Annotation` or `XML` instead.

**Pull request closed without merging**
