### PR TITLE
3.3.0

### PR DESCRIPTION
**Pull request by phansys**

### CODE REVIEW

**Comment by AkenRoberts** [comment]
There's a constant [in the code](https://github.com/doctrine-extensions/DoctrineExtensions/commit/8c02cee09e3dd43799ec3b84b619b19982c47f43#diff-f6b73756d4000fac126a313100caee883243c74034d76c5c33d5e2c826334254R29) with the current version, too. Heads up!

**Comment by phansys** [comment]
I'd like to include #2278 in this release, could you please take a look @AkenRoberts?
Thank you in advance.

**Comment by franmomu** [comment]
should we wait for https://github.com/doctrine-extensions/DoctrineExtensions/pull/2284 as well? since apparently requires a minor release and after this one users can use `doctrine/dbal` 3, I'll try to take a look at that PR later today.

**Comment by phansys** [comment]
>should we wait for #2284 as well? since apparently requires a minor release and after this one users can use doctrine/dbal 3, I'll try to take a look at that PR later today.

Sure! I'd love to include #2284 too. Even, I'd like to merge #2278 first in order to check the types #2284.

**Pull request merged**
