### PR TITLE
[bugfix] Add support for "date*_immutable" types

### PR DESCRIPTION
**Pull request by phansys**
|Q            |A     |
|---          |---   |
|Branch       |v2.4.x|
|Bug fix?     |yes   |
|New feature? |no    |
|BC breaks?   |no    |
|Deprecations?|no    |
|Tests pass?  |yes   |
|Fixed tickets|n/a   |
|License      |MIT   |
|Doc PR       |n/a   |

**TODO:**
- [x] Add tests;
- [x] ~~Update docs~~.

### CODE REVIEW

**Comment by phansys** [comment]
I need help to fix the tests (ODM). Any clue is welcome. Thank you in advance.

**Comment by phansys** [comment]
PHPUnit group "datetimeinterface" is excluded for php < 7.1 since support for "date*_immutable" types was added in `doctrine/dbal:2.6.0` (which requires PHP at 7.1+).
Failed tests seems related to Travis cache.

**Comment by phansys** [comment]
IMO, [**Codacy/PR**](https://app.codacy.com/app/stephanvierkant/DoctrineExtensions/pullRequest?prid=1457393) suggestions should be rejected.

**Comment by stephanvierkant** [comment]
I agree. Some rules are pointless:

> Avoid variables with short names like $id`

**Comment by phansys** [comment]
Is there something missing here? Any feedback is welcome.

**Comment by er1z** [comment]
Any news on this issue? It's weird.

**Comment by snoob** [comment]
Any news of this please ?

**Comment by phansys** [comment]
This PR is almost 3 years old.
I'm using my fork and with a custom repository in my dependencies in order to get this patch, because I need this change to get my soft-deletable models working..
Now, I need to upgrade `doctrine/common` to `^3.0`, which is compatible with the version 3 of this package, but I can't because this change is not merged there either.
Could you please help me to get this merged or point me in the right direction?

Friendly ping @stephanvierkant, as you are the only contributor participating in the review.

Thank you so much.

**Comment by svycka** [comment]
2.x version will not add new features only bugfixes. This should be rebased on the v3 version if it's not implemented there

**Comment by phansys** [comment]
Thank you @svycka. I'll take a look.

**Pull request closed without merging**
