### PR TITLE
Detect and respect integer values for onChange

### PR DESCRIPTION
**Pull request by holtkamp**
As suggested in https://github.com/doctrine-extensions/DoctrineExtensions/issues/2367#issuecomment-988683978

### CODE REVIEW

**Comment by phansys** [comment]
I'm fine with this change if you are able to cover all the possible cases and (ideally) delegating the type casting responsibility to Doctrine:
* https://github.com/doctrine/dbal/blob/2aec3f8da5f601462162d9b90d013554b240292b/src/Types/Types.php#L12-L36
* https://github.com/doctrine/mongodb-odm/blob/a520aaec89e7c12537f7bc56942976f35feaa4d4/lib/Doctrine/ODM/MongoDB/Types/Type.php#L27-L54

**Comment by holtkamp** [comment]
@phansys thanks for the input. Not sure whether I am up to this task, but first things first: when taking this path, probably the XML drivers of all extensions should be checked, right?

A [quick search](https://github.com/doctrine-extensions/DoctrineExtensions/blob/daebbcf27d909b5b1e8d394ec0e12bd181dcae85/src/Blameable/Mapping/Driver/Xml.php) gives me: 

- Blameable
- IpTraceable
- Timestampeable

Which seems reasonable... Do you think these 3 are all extensions that are affected?

**Comment by phansys** [comment]
Thank you for the analysis @holtkamp.

>Not sure whether I am up to this task

I'm sure you're up for this task. We are here to bring support if you need some help.

>first things first: when taking this path, probably the XML drivers of all extensions should be checked, right?

Yes, I think all the extensions hitting the same issue should share the same fix. Even if some case is missed in this iteration, we could create a new PR for border cases later.

**Comment by holtkamp** [comment]
As mentioned in https://github.com/doctrine-extensions/DoctrineExtensions/issues/2367#issuecomment-992601242 I still think it would be best to resolve https://github.com/doctrine-extensions/DoctrineExtensions/issues/2367 by making the mapping driver detect integers, but did not have any time / focus to work on this...

**Pull request closed without merging**
